sudo: false
language: node_js
node_js:
    - 8
    - 9
before_install:
    - curl -sf https://staging.qualityctl.run/install/eslint | BINDIR=. sh
before_script:
    - ./qctl-eslint .
script:
    - npm test
